extends RefCounted

enum Sound{
    NONE = -1, 
    CLOSEUP_OPEN = 0, 
    PHRASE_COLLECT_START = 1, 
    PHRASE_COLLECT_END = 2, 
    CLOSEUP_CLOSE = 3, 
    PHRASE_COLLECT_START_MORE = 4, 
    PHRASE_COLLECT_END_MORE = 5, 
    TYPEWRITER_LETTER = 6, 
    TYPEWRITER_SPACE = 7, 
    THINKING_TOGGLE_ON = 8, 
    THINKING_TOGGLE_OFF = 9, 
    CHARACTER_DISCOVERED = 10, 
    PHRASE_DRAG_START = 11, 
    PHRASE_DRAG_END = 12, 
    BUTTON_CLICK = 13, 
    TOOLTIP_OPEN = 14, 
    TOOLTIP_CLOSE = 15, 
    TIME_SWITCH = 16, 
    LOCATION_CHANGED = 17, 
    PRISON_ALARM = 18, 
    PUZZLE_SOLVED_CORRECTLY = 19, 
    PUZZLE_SOLVED_PARTIALLY = 20, 
    PUZZLE_SOLVED_INCORRECTLY = 21, 
    SCENARIO_UNLOCKED = 22, 
    SNIPPET_APPEARED_POSTER = 23, 
    SNIPPET_APPEARED_PAPER_PLANE = 24, 
    SNIPPET_APPEARED_BLOOD_VIAL = 25, 
    PUZZLE_UNLOCK_LOOP = 26, 
    SNIPPET_APPEARED_ENCYCLOPEDIA = 27, 
    SNIPPET_APPEARED_NEWSPAPER = 28, 
    SNIPPET_APPEARED_CASSETTE_PLAYER = 29, 
    SNIPPET_APPEARED_PHONE = 30, 
    SNIPPET_APPEARED_TRENCHCOAT = 31, 
    SCENARIO_EXPLORED = 32, 
    PUZZLE_PART_REVEALED = 33, 
    PUZZLE_SOLVED_PARTIALLY_IMPROVING = 34, 
    THINKING_CARD_CLICK = 35, 
    ELECTRIC_SHOCK = 36, 
    SNIPPET_APPEARED_CLOCK = 37, 
    SNIPPET_APPEARED_DISCS = 38, 
    SNIPPET_APPEARED_PAMPHLET = 39, 
    SNIPPET_APPEARED_HAT = 40, 
    SNIPPET_APPEARED_BUTTON_PHONE = 41, 
    SNIPPET_APPEARED_MONKEY_IDOL = 42, 
    SNIPPET_APPEARED_FRAMED_PHOTO = 43, 
    SNIPPET_APPEARED_WOLF = 44, 
    SNIPPET_APPEARED_COPTER = 45, 
    SNIPPET_APPEARED_IDOL_MACHINE = 46, 
    SNIPPET_APPEARED_KNIGHT = 47, 
    PUZZLE_SOLVED_PHRASE_HIGHLIGHT = 48, 
    PUZZLE_SOLVED_INDICATOR_BUILDUP = 49, 
    PUZZLE_SOLVED_CORRECTLY_END_SEQUENCE = 50, 
    CAR_IMPACT = 51, 
    TUTORIAL_PROGRESS = 52, 
    HINT_BREATHE = 53, 
}

enum TransitionSound{
    NONE = Sound.NONE, 
    DEFAULT = Sound.LOCATION_CHANGED, 
    TIME_SWITCH = Sound.TIME_SWITCH
}

enum SnippetSound{
    NONE = Sound.NONE, 
    POSTER = Sound.SNIPPET_APPEARED_POSTER, 
    PAPER_PLANE = Sound.SNIPPET_APPEARED_PAPER_PLANE, 
    BLOOD_VIAL = Sound.SNIPPET_APPEARED_BLOOD_VIAL, 
    ENCYCLOPEDIA = Sound.SNIPPET_APPEARED_ENCYCLOPEDIA, 
    NEWSPAPER = Sound.SNIPPET_APPEARED_NEWSPAPER, 
    CASSETTE_PLAYER = Sound.SNIPPET_APPEARED_CASSETTE_PLAYER, 
    PHONE = Sound.SNIPPET_APPEARED_PHONE, 
    TRENCHCOAT = Sound.SNIPPET_APPEARED_TRENCHCOAT, 
    CLOCK = Sound.SNIPPET_APPEARED_CLOCK, 
    DISCS = Sound.SNIPPET_APPEARED_DISCS, 
    PAMPHLET = Sound.SNIPPET_APPEARED_PAMPHLET, 
    HAT = Sound.SNIPPET_APPEARED_HAT, 
    BUTTON_PHONE = Sound.SNIPPET_APPEARED_BUTTON_PHONE, 
    MONKEY_IDOL = Sound.SNIPPET_APPEARED_MONKEY_IDOL, 
    FRAMED_PHOTO = Sound.SNIPPET_APPEARED_FRAMED_PHOTO, 
    WOLF = Sound.SNIPPET_APPEARED_WOLF, 
    COPTER = Sound.SNIPPET_APPEARED_COPTER, 
    IDOL_MACHINE = Sound.SNIPPET_APPEARED_IDOL_MACHINE, 
    KNIGHT = Sound.SNIPPET_APPEARED_KNIGHT, 
}

enum Transposition{
    DEFAULT = 0, 
    DOWN_ONE = 1, 
    UP_ONE = 2, 
}


static  var sound_map: Dictionary = {
    Sound.CLOSEUP_OPEN: SoundData.create("res://shared/assets/sfx/closeup_open.wav"), 
    Sound.CLOSEUP_CLOSE: SoundData.create("res://shared/assets/sfx/closeup_close.wav"), 
    Sound.PHRASE_COLLECT_START: SoundData.create("res://shared/assets/sfx/phrase_collect_start.wav"), 
    Sound.PHRASE_COLLECT_START_MORE: SoundData.create("res://shared/assets/sfx/phrase_collect_start_more.wav"), 
    Sound.PHRASE_COLLECT_END: SoundData.create("res://shared/assets/sfx/phrase_collect_end.wav"), 
    Sound.PHRASE_COLLECT_END_MORE: SoundData.create("res://shared/assets/sfx/phrase_collect_end_more.wav"), 
    Sound.THINKING_TOGGLE_ON: SoundData.create("res://shared/assets/sfx/thinking_toggle_on.wav"), 
    Sound.THINKING_TOGGLE_OFF: SoundData.create("res://shared/assets/sfx/thinking_toggle_off.wav"), 
    Sound.CHARACTER_DISCOVERED: SoundData.create("res://shared/assets/sfx/character_discovered.wav"), 
    Sound.PHRASE_DRAG_START: SoundData.create("res://shared/assets/sfx/phrase_drag_start.wav"), 
    Sound.PHRASE_DRAG_END: SoundData.create("res://shared/assets/sfx/phrase_drag_end.wav"), 
    Sound.BUTTON_CLICK: SoundData.create("res://shared/assets/sfx/button_click.wav"), 
    Sound.THINKING_CARD_CLICK: SoundData.create("res://shared/assets/sfx/thinking_card_click.wav"), 
    Sound.TOOLTIP_OPEN: SoundData.create("res://shared/assets/sfx/tooltip_open.wav"), 
    Sound.TOOLTIP_CLOSE: SoundData.create("res://shared/assets/sfx/tooltip_close.wav"), 
    Sound.TIME_SWITCH: SoundData.create("res://shared/assets/sfx/time_switch.wav"), 
    Sound.LOCATION_CHANGED: SoundData.create("res://shared/assets/sfx/location_changed.wav"), 
    Sound.PRISON_ALARM: SoundData.create("res://shared/assets/sfx/ambiences/prison_alarm_one_shot.ogg"), 
    Sound.PUZZLE_SOLVED_CORRECTLY: SoundData.create("res://shared/assets/sfx/puzzle_solved_correctly.wav", {
        Transposition.DOWN_ONE: "res://shared/assets/sfx/puzzle_solved_correctly_down_one.wav", 
        Transposition.UP_ONE: "res://shared/assets/sfx/puzzle_solved_correctly_up_one.wav"
    }), 
    Sound.PUZZLE_SOLVED_PARTIALLY: SoundData.create("res://shared/assets/sfx/puzzle_solved_partially.wav"), 
    Sound.PUZZLE_SOLVED_INCORRECTLY: SoundData.create("res://shared/assets/sfx/puzzle_solved_incorrectly.wav"), 
    Sound.PUZZLE_SOLVED_PARTIALLY_IMPROVING: SoundData.create("res://shared/assets/sfx/puzzle_solved_partially_improving.wav"), 
    Sound.SCENARIO_UNLOCKED: SoundData.create("res://shared/assets/sfx/scenario_unlocked.wav"), 
    Sound.SNIPPET_APPEARED_POSTER: SoundData.create("res://shared/assets/sfx/snippet_appeared_poster.wav"), 
    Sound.SNIPPET_APPEARED_PAPER_PLANE: SoundData.create("res://shared/assets/sfx/snippet_appeared_paper_plane.wav"), 
    Sound.SNIPPET_APPEARED_BLOOD_VIAL: SoundData.create("res://shared/assets/sfx/snippet_appeared_blood_vial.wav"), 
    Sound.SNIPPET_APPEARED_ENCYCLOPEDIA: SoundData.create("res://shared/assets/sfx/snippet_appeared_encyclopedia.wav"), 
    Sound.SNIPPET_APPEARED_NEWSPAPER: SoundData.create("res://shared/assets/sfx/snippet_appeared_newspaper.wav"), 
    Sound.SNIPPET_APPEARED_CASSETTE_PLAYER: SoundData.create("res://shared/assets/sfx/snippet_appeared_cassette_player.wav"), 
    Sound.SNIPPET_APPEARED_PHONE: SoundData.create("res://shared/assets/sfx/snippet_appeared_phone.wav"), 
    Sound.SNIPPET_APPEARED_TRENCHCOAT: SoundData.create("res://shared/assets/sfx/snippet_appeared_trenchcoat.wav"), 
    Sound.SCENARIO_EXPLORED: SoundData.create("res://shared/assets/sfx/scenario_explored.wav", {
        Transposition.DOWN_ONE: "res://shared/assets/sfx/scenario_explored_down_one.wav", 
        Transposition.UP_ONE: "res://shared/assets/sfx/scenario_explored_up_one.wav"
    }), 
    Sound.PUZZLE_PART_REVEALED: SoundData.create("res://shared/assets/sfx/puzzle_part_revealed.wav"), 
    Sound.TYPEWRITER_LETTER: SoundData.create("res://shared/assets/sfx/typewriter_letter.wav"), 
    Sound.TYPEWRITER_SPACE: SoundData.create("res://shared/assets/sfx/typewriter_space.wav"), 
    Sound.PUZZLE_UNLOCK_LOOP: SoundData.create("res://shared/assets/sfx/puzzle_unlock_particle_loop.wav"), 
    Sound.ELECTRIC_SHOCK: SoundData.create("res://shared/assets/sfx/ambiences/electric_shock_one_shot.ogg"), 
    Sound.SNIPPET_APPEARED_CLOCK: SoundData.create("res://shared/assets/sfx/snippet_appeared_clock.wav"), 
    Sound.SNIPPET_APPEARED_DISCS: SoundData.create("res://shared/assets/sfx/snippet_appeared_discs.wav"), 
    Sound.SNIPPET_APPEARED_PAMPHLET: SoundData.create("res://shared/assets/sfx/snippet_appeared_pamphlet.wav"), 
    Sound.SNIPPET_APPEARED_HAT: SoundData.create("res://shared/assets/sfx/snippet_appeared_hat.wav"), 
    Sound.SNIPPET_APPEARED_BUTTON_PHONE: SoundData.create("res://shared/assets/sfx/snippet_appeared_button_phone.wav"), 
    Sound.SNIPPET_APPEARED_FRAMED_PHOTO: SoundData.create("res://shared/assets/sfx/snippet_appeared_framed_photo.wav"), 
    Sound.SNIPPET_APPEARED_MONKEY_IDOL: SoundData.create("res://shared/assets/sfx/snippet_appeared_monkey_idol.wav"), 
    Sound.SNIPPET_APPEARED_WOLF: SoundData.create("res://shared/assets/sfx/snippet_appeared_wolf.wav"), 
    Sound.SNIPPET_APPEARED_COPTER: SoundData.create("res://shared/assets/sfx/snippet_appeared_copter.wav"), 
    Sound.SNIPPET_APPEARED_IDOL_MACHINE: SoundData.create("res://shared/assets/sfx/snippet_appeared_idol_machine.wav"), 
    Sound.SNIPPET_APPEARED_KNIGHT: SoundData.create("res://shared/assets/sfx/snippet_appeared_knight.wav"), 
    Sound.PUZZLE_SOLVED_PHRASE_HIGHLIGHT: SoundData.create("res://shared/assets/sfx/puzzle_solved_phrase_highlight.wav"), 
    Sound.PUZZLE_SOLVED_INDICATOR_BUILDUP: SoundData.create("res://shared/assets/sfx/puzzle_solved_indicator_buildup.wav"), 
    Sound.PUZZLE_SOLVED_CORRECTLY_END_SEQUENCE: SoundData.create("res://shared/assets/sfx/puzzle_solved_correctly_end_sequence.wav"), 
    Sound.CAR_IMPACT: SoundData.create("res://shared/assets/sfx/car_impact.wav"), 
    Sound.TUTORIAL_PROGRESS: SoundData.create("res://shared/assets/sfx/tutorial_progress.wav"), 
    Sound.HINT_BREATHE: SoundData.create("res://shared/assets/sfx/ambiences/hint_breathe_one_shot.ogg"), 
}
